[package]
name = "turbostore"
version = "0.1.0"
edition = "2024"

[dependencies]
bitcode = "0.6.6"
chrono = "0.4.41"
scc = "2.3.4"

[dev-dependencies]
pollster = { version = "0.4.0", features = ["macro"] }
